### ISSUE TITLE
Replace CSV with yaml

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DSAC#21]
This is just an issue to track the idea and discuss using yaml instead of CSV.

**Comment by MagicalCodeMonkey** [comment]
Keep open

**Comment by MagicalCodeMonkey** [comment]
#26 - Not quite YAML but a step in the right direction

**Comment by MagicalCodeMonkey** [comment]
No, I'm just busy with other things!

**Comment by MagicalCodeMonkey** [comment]
Still working on it, bot!
