### ISSUE TITLE
Bug: Incorrect Jackett Torzab URL

### ISSUE THREAD

**Issue by idolize** [GhostWriters/DSAC#29]
**Describe the bug**
The default config for Radarr is incorrect in how it talks to Jackett - it tries to use `[IP:port]/torznab/api` but that always results in an error.

According to the [Jackett docs](https://github.com/Jackett/Jackett#aggregate-indexers) the correct URL is `[IP:port]/api/v2.0/indexers/all/results/torznab`.

Changing it to this fixes the issue.

**To Reproduce**

- Run the stock "TV Series & Movies" setup from the DSAC Menu
- Run "Test" in Radarr for the DSAC Jackett indexer **-- Failure**
- Try to query for a movie in Radarr
- Check Radarr logs **-- Observe failure**

**Expected behavior**
Use the correct URL for the index

**Screenshots**
<img width="1192" alt="Screen Shot 2020-03-31 at 3 48 11 PM" src="https://user-images.githubusercontent.com/635005/78082551-315a0e80-7368-11ea-84e6-a1ec196cc83b.png">

**System**

- OS: Raspbian
- Version 10 (buster)

**Additional context**

Likely the "indexer base" on this line https://github.com/GhostWriters/DSAC/blob/a05c0f5d67d0714587382744b68b168002a41aab/.scripts/configure_add_indexer.sh#L35

**Comment by MagicalCodeMonkey** [comment]
Working on fixing this as I refactor things for #21
